---
abstract: 'get, unpack, build and install modules from CPAN'
author:
  - '- Tatsuhiko Miyagawa'
build_requires:
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Milla version v1.0.2, Dist::Zilla version 4.300034, CPAN::Meta::Converter version 2.130880'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-cpanminus
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
requires:
  ExtUtils::Install: 1.46
  ExtUtils::MakeMaker: 6.31
  Module::Build: 0.36
resources:
  bugtracker: https://github.com/miyagawa/cpanminus/issues
  homepage: https://github.com/miyagawa/cpanminus
  repository: https://github.com/miyagawa/cpanminus.git
version: 1.6909
x_contributors:
  - 'Alessandro Ghedini <al3xbio@gmail.com>'
  - 'Andrew Rodland <andrew@cleverdomain.org>'
  - 'Ash Berlin <ash_github@firemirror.com>'
  - 'Ben Bullock <benkasminbullock@gmail.com>'
  - 'Christian Walde <walde.christian@googlemail.com>'
  - 'Dagfinn Ilmari Mannsåker <ilmari@ilmari.org>'
  - 'Dave Goodell <davidjgoodell@gmail.com>'
  - 'Dave Rolsky <autarch@urth.org>'
  - 'Fuji, Goro <g.psy.va@gmail.com>'
  - 'Ingy dot Net <ingy@ingy.net>'
  - 'J. Nick Koston <nick@cpanel.net>'
  - 'Jan Dubois <jand@activestate.com>'
  - 'Jeffrey Ryan Thalhammer <jeff@imaginative-software.com>'
  - 'Jesse Luehrs <doy@tozt.net>'
  - 'Jonathan Scott Duff <duff@pobox.com>'
  - 'Kenichi Ishigaki <ishigaki@cpan.org>'
  - 'Kent Fredric <kentnl@cpan.org>'
  - 'Larry Leszczynski <larryl@atomiclearning.com>'
  - 'Masahiro Nagano <kazeburo@gmail.com>'
  - 'Masayoshi Sekimura <sekimura@gmail.com>'
  - 'Matt S Trout <>'
  - 'Matt S Trout <mst@shadowcat.co.uk>'
  - 'Michael G. Schwern <schwern@pobox.com>'
  - 'Norman Nunley <nnunley@gmail.com>'
  - 'Olaf Alders <olaf@wundersolutions.com>'
  - 'Pedro Melo <melo@simplicidade.org>'
  - 'Rafal Pocztarski <r.pocztarski@gmail.com>'
  - 'Ricardo Signes <rjbs@cpan.org>'
  - 'Rob Hoelz <rob@hoelz.ro>'
  - 'Robert Buels <rmb32@cornell.edu>'
  - 'Roman Jurkov <rjurkov@verio.net>'
  - 'Smylers <Smylers@stripey.com>'
  - 'Stoned Elipot <stoned.elipot@gmail.com>'
  - 'Tatsuhiko Miyagawa <miyagawa@gmail.com>'
  - 'Thomas Sibley <tom@zulutango.org>'
  - 'Tokuhiro Matsuno <tokuhirom@gmail.com>'
  - 'Vyacheslav Matyukhin <mmcleric@yandex-team.ru>'
  - 'Yann Kerherve <yann@cyberion.net>'
  - 'cho45 <cho45@lowreal.net>'
  - 'chromatic <chromatic@wgz.org>'
  - 'fREW Schmidt <frioux@gmail.com>'
  - 'gfx <gfuji@cpan.org>'
  - 'ikasam_a <masaki.nakagawa@gmail.com>'
  - 'jonallen <jj@jonallen.info>'
  - 'kmx <kmx@cpan.org>'
  - 'lestrrat <lestrrat+github@gmail.com>'
  - 'motemen <motemen@gmail.com>'
  - 'reezer <kind@gmx.at>'
  - 'robario <webmaster@robario.com>'
  - 'vti <viacheslav.t@gmail.com>'
  - 'xaicron <xaicron@gmail.com>'
  - 'yappo <yappo@shibuya.pl>'
